name: keepalive
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch:        # lets you run it manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl health endpoint
        run: |
          curl -sS --max-time 10 https://www.berriesllc.com/health || true
